Added partitioner, fixed bug in SPDHG and added info about warmstart
TomographicImaging/CIL-Demos pull request #134
Opened 2023-08-31 11:03 UTC by MargaretDuff

2023-09-22 15:04 UTC, MargaretDuff commented
@gfardell or @lauramurgatroyd - can you just double check this before I merge

2023-09-25 08:13 UTC, lauramurgatroyd requested changes
I have requested some changes, but also, we can't merge until we have the new release of CIL with the new warm_start parameter.

2023-09-25 08:13 UTC, lauramurgatroyd commented on demos/2_Iterative/03_PDHG.ipynb
> +    "- Using the TotalVariation class, from CIL. This solves the TV denoising problem (using the FGP algorithm) in CPU. The default warmstart=True, means that the TV denoising problem is initialised
```suggestion
    "- Using the TotalVariation class, from CIL. This solves the TV denoising problem (using the FGP algorithm) in CPU. The default warm_start=True, means that the TV denoising problem is initialised each time with the solution of the previous run of the TV denoising problem. This means we can use as few as 10 iterations of FGP and increases computation speed. \n",
```

2023-09-25 08:13 UTC, lauramurgatroyd commented on demos/2_Iterative/04_SPDHG.ipynb
You need to run nbstripout on this file before committing it, so that the outputs are removed. As it is, the diff is too big for me to see what you changed.

2023-09-25 08:17 UTC, MargaretDuff commented
> I have requested some changes, but also, we can't merge until we have the new release of CIL with the new warm_start parameter.

Thanks @lauramurgatroyd - that is an excellent point :)

2023-09-25 08:55 UTC, MargaretDuff commented on demos/2_Iterative/04_SPDHG.ipynb
Thanks @lauramurgatroyd - Think I have done this now. Let's wait until the new CIL release

2024-07-04 09:38 UTC, lauramurgatroyd commented
Hi, are we able to merge this now?

2024-07-04 09:44 UTC, MargaretDuff commented
I think so, `warm_start` got added 23.1.0 which is what we recommend currently for the notebooks

2024-09-05 15:55 UTC, lauramurgatroyd requested changes
Most of these files have their outputs rendered - please remove this before merging

2024-09-06 09:51 UTC, MargaretDuff commented
Superseded by #165

2024-09-06 09:51 UTC, closed without merging