New how to: step sizes and  preconditioners
TomographicImaging/CIL-Demos pull request #177
Opened 2024-10-01 14:45 UTC by MargaretDuff

How-to on step sizes and preconditioners for GD, ISTA and FISTA. 

It can be reviewed but probably needs to wait until after  #1934 is merged and released to use this notebook

2024-10-10 15:27 UTC, lauramurgatroyd requested changes
Great use of contours and 3D plots in the explanations

had some issues with things not running when removing alpha even though I was using CIL master. I would like to review again once that has been fixed

2024-10-10 15:27 UTC, lauramurgatroyd commented on demos/2_Iterative/07_how_to_preconditioner_stepsize.ipynb
> +    "## Gradient descent with a fixed step size \n",
In the first figure here you label the result as L2 Regularised. However the title of this section is Tikhonov. I know the eqn clearly shows L2 is being used but it doesn't say it anywhere in the text until its a figure title. I wonder if we need to expand text to mention L2 or instead label the figure as Tikhonov Regularised

2024-10-10 15:27 UTC, lauramurgatroyd commented on demos/2_Iterative/07_how_to_preconditioner_stepsize.ipynb
> +    "algo_GD_lip=GD(initial=ig.allocate(0), objective_function=F, step_size=1/F.L )\n",
I think it would be good to add some info about L being a property, or link to the docs on it
https://tomographicimaging.github.io/CIL/nightly/optimisation/#cil.optimisation.functions.Function.L

2024-10-10 15:27 UTC, lauramurgatroyd commented on demos/2_Iterative/07_how_to_preconditioner_stepsize.ipynb
> +    "This does not work because in 40 iterations, the Armijo step size rule as not found a suitable step size. We can alter the number of iterations in the step size rule to allow it to run without e
```suggestion
    "This does not work because in 40 iterations, the Armijo step size rule has not found a suitable step size. We can alter the number of iterations in the step size rule to allow it to run without error: "
```

2024-10-10 15:27 UTC, lauramurgatroyd commented on demos/2_Iterative/07_how_to_preconditioner_stepsize.ipynb
> +    "where $ f $ is the objective function, $ x_k $ is the current point, $ \\alpha_k $ is the step size, $\\nabla f(x_k)$ is the search direction, and $c $ is a constant typically chosen in the inte
Here the figure is labelled Tik, above we labelled as L2, we need consistency

2024-10-10 15:27 UTC, lauramurgatroyd commented on demos/2_Iterative/07_how_to_preconditioner_stepsize.ipynb
> +    "algo_default=GD(initial=ig.allocate(0), objective_function=F , alpha=1e8) # TODO: once #1934 is merged remove the alpha argument\n",
Still not working when alpha is removed - on CIL master

2024-10-10 15:27 UTC, lauramurgatroyd commented on demos/2_Iterative/07_how_to_preconditioner_stepsize.ipynb
> +    "The reason this is an ellipse is due to the fact that the matrix $A$ is ill-conditions, it acts with a greater magnitude in some directions than other directions."
```suggestion
    "The reason this is an ellipse is due to the fact that the matrix $A$ is ill-conditioned, it acts with a greater magnitude in some directions than other directions."
```

Should it be ill-conditioned instead?

2024-10-10 15:27 UTC, lauramurgatroyd commented on demos/2_Iterative/07_how_to_preconditioner_stepsize.ipynb
> +    "plt.title('Non-preconditioned loss landscape')\n",
```suggestion
    "plt.title('preconditioned loss landscape')\n",
```

2024-10-10 15:27 UTC, lauramurgatroyd commented on demos/2_Iterative/07_how_to_preconditioner_stepsize.ipynb
> +    "algo_precon=GD(initial=ig.allocate(0), objective_function=F , preconditioner=precon, alpha=1e8) # TODO: once #1934 is merged remove the alpha argument \n",
```suggestion
    "algo_precon=GD(initial=ig.allocate(0), objective_function=F , preconditioner=precon)
```
this worked for me without alpha

2024-10-10 15:27 UTC, lauramurgatroyd commented on demos/2_Iterative/07_how_to_preconditioner_stepsize.ipynb
> +    "show2D([ground_truth, recon, algo.solution], title = ['Ground Truth', 'FDK Reconstruction', 'Tik solution'], origin = 'upper', num_cols = 3)"
```suggestion
    "show2D([ground_truth, recon, algo_precon.solution], title = ['Ground Truth', 'FDK Reconstruction', 'Tik solution'], origin = 'upper', num_cols = 3)"
```

2024-10-16 14:15 UTC, MargaretDuff commented on demos/2_Iterative/07_how_to_preconditioner_stepsize.ipynb
> +    "algo_GD_lip=GD(initial=ig.allocate(0), objective_function=F, step_size=1/F.L )\n",
Thanks Laura!

2024-10-16 14:22 UTC, MargaretDuff commented on demos/2_Iterative/07_how_to_preconditioner_stepsize.ipynb
> +    "where $ f $ is the objective function, $ x_k $ is the current point, $ \\alpha_k $ is the step size, $\\nabla f(x_k)$ is the search direction, and $c $ is a constant typically chosen in the inte
Good spot!

2024-10-16 14:22 UTC, MargaretDuff commented on demos/2_Iterative/07_how_to_preconditioner_stepsize.ipynb
> +    "## Gradient descent with a fixed step size \n",
Thanks Laura - I made this more consistent

2024-10-16 15:22 UTC, MargaretDuff commented
@lauramurgatroyd - should now work on 24.2.0 - and ready for another review!

2024-10-16 15:43 UTC, lauramurgatroyd reviewed
Changes look great, sorry just spotted one thing

2024-10-16 15:43 UTC, lauramurgatroyd commented on demos/04_Deep_Dives/02_preconditioner_stepsize.ipynb
> +    "class mean_squared_errror_callback(callbacks.Callback):\n",
I'm sorry but error has too many r's!!

2024-10-16 15:45 UTC, MargaretDuff commented on demos/04_Deep_Dives/02_preconditioner_stepsize.ipynb
> +    "class mean_squared_errror_callback(callbacks.Callback):\n",
Good spot!

2024-10-16 16:10 UTC, lauramurgatroyd approved these changes

2024-10-29 10:39 UTC, MargaretDuff commented
I think the path needs to be '4_Deep_Dives/04_preconditioner_stepsize.ipynb'

2024-10-29 14:34 UTC, effepivi commented
Overall, it is very good. I have a few minor comments:

- I think a small introductory paragraph is needed.

- In 
```
Now consider a more sensible choice of fixed step size, the reciprocal of the Lipschitz constant of
. In CIL, where it is available or easily calculable, the Lipschitz constant of a function is stored as property of the CIL function, for more info see the documentation: https://tomographicimaging.github.io/CIL/nightly/optimisation/#cil.optimisation.functions.Function.L
```
I think a bit more info (e.g. a line or half a line) on the Lipschitz constant is required. The main audience is the tomography in a wide sense. Not providing the info means people should be familiar with it already. For example, I find "the Armijo step size rule. This is a "backtracking" line search method" less frustrating to read. A lot of people won't be familiar with these terms.

- Add a comment between the two cells as follows to explain what is your aim when doing the plot:



alpha=0.1
A = ProjectionOperator(image_geometry=ig, 
                       acquisition_geometry=absorption.geometry)

```
F = 0.5*LeastSquares(A = A, b = absorption)+ alpha*L2NormSquared()
step_size_rule=ArmijoStepSizeRule(max_iterations=50)
algo_default=GD(initial=ig.allocate(0), objective_function=F, step_size=step_size_rule)
algo_default.run(50)
show2D([ground_truth, recon, algo_default.solution], title = ['Ground Truth', 'FDK Reconstruction', 'L2 regularised solution'], origin = 'upper', num_cols = 3)
```

```
plt.plot(range(2,51),algo_GD_fixed.objective[2:], label='Fixed step size = 1e-6')
plt.plot(range(2,51),algo_GD_lip.objective[2:], label='Fixed step size = 1/L')
plt.plot(range(2,51),algo_default.objective[2:], label='Armijo rule')
plt.legend()

plt.xlabel('Iteration')
plt.ylabel('Objective value')
```

- Any idea what the accpetable value ranges are in:
```
    __init__(self, initial=0.1, shrinkage=0.999): Initializes the step size rule with an initial step size and a shrinkage factor.
        initial (float): The initial step size to be used in the first iteration. Default is 0.1.
        shrinkage (float): The factor by which the step size is multiplied at each iteration. Default is 0.999.
```
0.999 is almost 1.0, but not quite. It raises questions.

- Again, I think it is good to explain what you want people to identify before the plot. (the why).
```
plt.plot(range(5,51),algo_GD_fixed.objective[5:], label='Fixed step size = 1e-6')
plt.plot(range(5,51),algo_GD_lip.objective[5:], label='Fixed step size = 1/L')
plt.plot(range(5,51),algo_default.objective[5:], label='Armijio rule')
plt.plot(range(5,51),algo_custom.objective[5:], label='Custom rule')
plt.xlabel('Iteration')
plt.ylabel('Objective value')
plt.legend()
```

- In the matrix, you use 0.0 twice, I would use 1.0 instead of 1 for consistency.

2024-10-29 16:35 UTC, MargaretDuff commented
Thanks for your comments Franck! I think I have addressed them but need to rerun the notebook once the VMs are back online (fingers crossed)

2024-10-30 21:37 UTC, jakobsj approved these changes
Looks great to me from a quick readthrough - no comments!

2024-10-31 08:45 UTC, merged