Add ZeissDataReader how to
TomographicImaging/CIL-Demos pull request #179
Opened 2024-10-01 15:23 UTC by hrobarts

2024-10-22 09:34 UTC, lauramurgatroyd approved these changes
Again, like the Nikon reader, I think this is a great example

Only thing not covered is get_geometry (see Nikon reader)
And again, not sure what was the outcome of whether to render here or not 😄

2024-10-22 14:06 UTC, M-A-Demir approved these changes

2024-10-23 11:28 UTC, M-A-Demir requested changes
Spelling error in cell [-3]? " Sometimes we might want to just **reader** the geometry ... "

Otherwise, looks good! :)

2024-10-23 14:35 UTC, M-A-Demir approved these changes

2024-10-23 14:36 UTC, hrobarts commented
> Spelling error in cell [-3]? " Sometimes we might want to just **reader** the geometry ... "
> 
> Otherwise, looks good! :)

Good spot! Fixed this now

2024-10-23 14:49 UTC, merged