New deep dive - directional TV
TomographicImaging/CIL-Demos pull request #212
Opened 2024-11-08 16:30 UTC by MargaretDuff

Needs some more work. Potentially to write the dTV regulariser in CIL? To show some metrics, try some downsampling or show a wider range of regularisation parameters?

2025-02-06 21:21 UTC, jakobsj requested changes
Great notebook illustrating many aspects including not only directional TV, but both a version from the regularisation toolkit, build yourself in plain CIL, composition of blur and projection in a projection operator. Overall in great shape already, here my initial suggestions from only reading without running it (couldn't get inline commenting to work so listing everything here sorry)

- Add list of 3-5 learning objective or Topics Covered or similar to highlight visually the key bits of what is now written in the initial paragraph.
- As is 2D, should better say fan-beam instead of cone-beam.
- Not sure if one is "more correct" or "better", but was slightly surprised with the blurring being applied first, followed by projection operator. I would have found the opposite more natural. Any particular reason for this choice/was the opposite tried?
- Some cells in the beginning have been run as the output cell numbers shows, please clear.
- For keyword input arguments seemingly some inconsistent spacing around "=", sometimes with spaces (for example in show2D calls), sometimes without. I suggest removing all spaces throughout.
- Similarly, for defining variable I suggest always having spaces surrounding "=" for example where `forward` is defined.
- For the blurring operator, I think it would be helpful to the reader to initially demonstrate the effect of just that onto a sharp image before applying the projection operator (that is if the order of the operators is kept, see previous comment)
- For the text before the FDK cell, I get the point but I think the phrase "we use the tomography forward model" can be misleading since with FDK we do not USE any forward model, perhaps could say FDK assumes data arises from only a tomography forward model/FDK does not incorporate inversion of the blurring part, only the tomography part.
- In general, after each show2D call I miss a short explanation of what the main observations from the resulting figures are. Only after the dTV results I see such observations listed (here should clarify that these "Too small a value..." are observations we see from the resulting images, not general truths.)
- The last part with building dTV in CIL has the opportunity to be excellent,  it is the most complicated yet the shortest, I would suggest expanding the explanation substantially here and splitting in multiple cells to be described separately. For example can we evaluate the regu toolkit dTV and the CIL one (not run optimisation, just evaluate function value to demonstrate they produce the same for validation). All of the steps with PDHG and a complicated block operator would benefit from more explanation since a reader will not necessarily be super familiar with this.
- I don't understand the last part "With less information..." what is the information we are missing here and compared to when? I think this possibly related to the final note that the notebook is not complete, but I think it needs to be explained a bit more.
- Typo: "we now compose the two opertors"
- Typo: "definethe"
- In the description of dTV "The idea..." I suggest elaborating and clarifying a bit. Being a bit strict dTV is not only small in the case where ALL gradients are parallel, somehow should say that it is gradually smaller as more gradients are parallel.
- In dTV notation, "dTV" should be nonitalic.
- D_i is in the formula, but below only D is explained.
- Should say that eta is a scalar smoothing parameter to ensure that the denominator is not zero.
- The current description is in a classic concise math style where the formula is given, then all symbols very compactly described. I think the description might be clearer to more of our readers if building it up in the opposite way by (after an initial sentence or two on what the overall idea is) the introduce and illustrate each of the building blocks x, zeta, D, nu etc are before combining and providing the dTV definition.
- I don't immediately understand the last two sentences "We can see that ... " and "We can also see that ..." again rather math-y, can the reasoning and relevance to the reader of these derivations be elaborated in text to the reader?
- Second to last sentence "... encourages  the gradients of ..." is very helpful in explaining the motivation of dTV, perhaps could be moved up to the beginning of the dTV section.
- For the reference image, I don't immediately understand - is it the same image as we are reconstructing? Is it the same but with different values? Can this be explained in the notebook.

2025-02-07 07:49 UTC, epapoutsellis commented
- At the beginning `G`  is a blurring operator and then inside the loop after *FISTA+TV Recon* is `FGP_TV`. Maybe use `B` for the blurring.
-  Since you compute 
> ```
>   Grad = BlockOperator(DY, DX)
>   grad_ref = Grad.direct(reference)
>   denom = (eta**2 + grad_ref.pnorm(2)**2).sqrt()
>   xi = grad_ref/denom
>   ```
it would be nice to see the effect of `xi` for different values of `eta`.
- If you want to focus on the optimisation, callbacks, distance from optimal I have [CVX corresponding problem](https://github.com/epapoutsellis/CIL_and_CVXPY/blob/main/DirectionalTotalVariation.ipynb) for the denoising case. 
- Maybe an alternative or exercise is to use a real dataset/sinogram (A):
     - create a sinogram (B) with few angles and FBP reconstruct to show artifacts.
     - use dTV (in the denoising case) with an FBP from (A) as a reference.

2025-03-04 16:08 UTC, MargaretDuff commented
Thanks @epapoutsellis  and @jakobsj - I think I have updated, dealing with all your comments. 

@jakobsj r.e. the odd decision to blur before the tomography forward operator, not after, I think that was because this notebook was originally written for a SIRF training course so the focus was on PET where the emission could be considered "blurry" around areas of interest in the body. What do you think? 

@epapoutsellis - I left it as an exercise to investigate the effect of xi for different eta values. I think you are right that some callbacks/numerical comparisons might also be useful. I don't want to add more complexity with cvxpy but will have a think about a potential metric to plot.

2025-03-17 08:45 UTC, jakobsj approved these changes
Many thanks @MargaretDuff, as far as I can see all comments addressed very nicely and the notebook reads very well with clear explanations of the math and the observations from the figures.

2025-03-18 15:37 UTC, lauramurgatroyd reviewed
"Thus for each point in the image space we have a normalised direction, with horizontal and vertical component, as to the gradients in the reference image. " - sorry I don't quite understand what this means 


Please add comparison with fgp_dtv and cil dtv

2025-03-18 15:37 UTC, lauramurgatroyd commented on demos/4_Deep_Dives/05_directional_TV.ipynb
> +    "For the forward model, we will include both a tomographic projection and a blurr. In the next cell, we define a point spread function and pass this to the CIL `BlurringOperator`."
```suggestion
    "For the forward model, we will include both a tomographic projection and a blur. In the next cell, we define a point spread function and pass this to the CIL `BlurringOperator`."
```

2025-03-18 15:37 UTC, lauramurgatroyd commented on demos/4_Deep_Dives/05_directional_TV.ipynb
> +    "       'Absorption', 'Noisy absorption'], origin='upper', num_cols=2);"
```suggestion
    "       'Absorption', 'Noisy and Blurred absorption'], origin='upper', num_cols=2);"
```

2025-03-18 15:37 UTC, lauramurgatroyd commented on demos/4_Deep_Dives/05_directional_TV.ipynb
> +    " where $B$ is the blurring operator, $A$ the tomographic projection, $ y$ the noisy measured data and $g$ is the TV regulariser with regularisation paramater $\\alpha$. \n",
```suggestion
    " where $B$ is the blurring operator, $A$ the tomographic projection operator, $ y$ the noisy measured data and $g$ is the TV regulariser with regularisation paramater $\\alpha$. \n",
```

I think A is an operator?

2025-03-18 15:37 UTC, lauramurgatroyd commented on demos/4_Deep_Dives/05_directional_TV.ipynb
> +    "plt.show()"
Please add plot titles

2025-03-20 15:33 UTC, lauramurgatroyd approved these changes
Looks good

2025-03-20 15:33 UTC, lauramurgatroyd commented on demos/4_Deep_Dives/05_directional_TV.ipynb
> +    "For each point in the image space we now have a direction of normalised length, described by a horizontal and vertical component, in the same direction as the gradient of the reference image at
This is very clear now, thanks!

2025-03-20 15:33 UTC, lauramurgatroyd commented on demos/4_Deep_Dives/05_directional_TV.ipynb
> +    "### Excercise \n",
exercise - typo

2025-03-20 16:41 UTC, merged