added notebook for dXCT 22
TomographicImaging/CIL-Demos pull request #85
Opened 2022-06-10 11:17 UTC by paskino

I put it in misc, maybe we need a better directory?

2022-06-10 14:31 UTC, lauramurgatroyd requested changes

2022-06-10 14:31 UTC, lauramurgatroyd commented on misc/Walnut2d.ipynb
> +    "Reduce the amount of projection to 10% by selecting a projection every 10."
```suggestion
    "Reduce the amount of projections to 10% by selecting 1 projection in every 10."
```

2022-06-10 14:31 UTC, lauramurgatroyd commented on misc/Walnut2d.ipynb
> +    "A = ProjectionOperator(ig,data_reduced.geometry)"
Here I get an error that ig is not defined

2022-06-10 16:29 UTC, lauramurgatroyd commented
Not sure if it's just me but i reloaded a couple of times and still having a problem with the equations not formatting correctly:
![image](https://user-images.githubusercontent.com/60604372/173110635-9712deb9-ac19-47f2-a054-a5baff35711c.png)

2022-06-28 08:45 UTC, paskino commented
Maybe this can become our first tutorial

2022-11-11 14:48 UTC, jakobsj commented
@paskino Is this one still relevant? If it was used at dXCT we should get it in to have a record of it.

2022-11-25 12:04 UTC, lauramurgatroyd commented
If I remember correctly, I don't think it was used in the end?

2023-02-22 11:21 UTC, closed without merging